const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

function generatePDF() {
    const doc = new PDFDocument({ margin: 50 });
    const outputPath = path.join(__dirname, 'project_summary.pdf');
    const stream = fs.createWriteStream(outputPath);

    doc.pipe(stream);

    // --- COLORS ---
    const primary = '#FF9933'; // Spiritual Saffron
    const secondary = '#6366F1'; // Modern Indigo
    const accent = '#FFD700'; // Divine Gold
    const bgDark = '#0F172A';
    const textMain = '#334155';
    const textDim = '#64748B';

    // --- HEADER ---
    doc.rect(0, 0, 612, 100).fill(bgDark);
    doc.fillColor(primary).fontSize(28).text('Krishna says', 50, 35, { characterSpacing: 1 });
    doc.fillColor('white').fontSize(12).text('Project Technical Report', 50, 70);
    doc.moveDown(4);

    // --- OVERVIEW ---
    doc.fillColor(primary).fontSize(18).text('Project Overview', { underline: true });
    doc.moveDown(0.5);
    doc.fillColor(textMain).fontSize(11).text(
        'Krishna says is a high-end web application designed to provide spiritual and philosophical guidance. ' +
        'It utilizes modern web technologies and a glassmorphism design language to create an immersive user experience.'
    );
    doc.moveDown();

    // --- DESIGN SYSTEM ---
    doc.fillColor(primary).fontSize(16).text('Design System & Branding');
    doc.moveDown(0.5);
    
    const drawColorRect = (color, label, y) => {
        doc.fillColor(color).rect(50, y, 20, 20).fill();
        doc.fillColor(textMain).fontSize(10).text(`${label}: ${color}`, 80, y + 5);
    };

    drawColorRect(primary, 'Primary (Saffron)', doc.y);
    drawColorRect(secondary, 'Secondary (Indigo)', doc.y + 10);
    drawColorRect(accent, 'Accent (Gold)', doc.y + 10);
    doc.moveDown(2);

    // --- FILE STRUCTURE ---
    doc.fillColor(primary).fontSize(16).text('Project Structure');
    doc.moveDown(0.5);
    const files = fs.readdirSync(__dirname).filter(file => 
        !file.startsWith('.') && 
        file !== 'node_modules' && 
        file !== 'package-lock.json' &&
        file !== 'project_summary.pdf' &&
        file !== 'generate_pdf.js' &&
        file !== 'test_output.txt'
    );

    files.forEach(file => {
        doc.fillColor(textMain).fontSize(11).text(`  • ${file}`);
    });
    doc.moveDown();

    // --- KEY FEATURES ---
    doc.fillColor(primary).fontSize(16).text('Key Features');
    doc.moveDown(0.5);
    doc.fillColor(textMain).fontSize(10).list([
        'Multi-Agent System (Auth, Profile, Wisdom, Safety, UI)',
        'Mood-Aware AI Guidance (Neutral, Anxious, Confused, Ambitious, Peaceful)',
        'Immersive Temple Mode (Zen UI) with Backdrop Blurs',
        'Audio System: Ambient Background Sounds (Flute, Nature, Chants)',
        'Spiritual Journal: Persistent Favorites with Personal Reflections',
        'Wallet & Subscription System (Razorpay/Stripe Simulation)',
        'Three-Stage Mandatory Legal Disclaimers',
        'Verse of the Day Widget on Dashboard',
        'High-End Glassmorphism Design Language',
        'Voice Interaction (TTS) & Multi-language Support (EN/HI/GU)'
    ]);
    doc.moveDown();

    // --- TECHNICAL STACK ---
    doc.fillColor(primary).fontSize(16).text('Technical Stack');
    doc.moveDown(0.5);
    doc.fillColor(textMain).fontSize(11).list([
        'Frontend: Semantic HTML5, CSS3 (Glassmorphism)',
        'Logic: Modern ES6+ JavaScript',
        'Environment: Node.js (Development Server)',
        'Testing: Vitest, JSDOM for UI assertions',
        'PDF Engine: PDFKit'
    ]);
    doc.moveDown();

    // --- TEST RESULTS ---
    if (fs.existsSync(path.join(__dirname, 'test_output.txt'))) {
        doc.addPage();
        doc.fillColor(primary).fontSize(18).text('Validation & Test Results', { underline: true });
        doc.moveDown(0.5);
        const testOutput = fs.readFileSync(path.join(__dirname, 'test_output.txt'), 'utf8');
        doc.fillColor(textDim).fontSize(9).text(testOutput.substring(0, 3000), { font: 'Courier' });
    }

    // --- FOOTER FUNCTION ---
    const addFooter = (doc, pageNum, totalPages) => {
        doc.fillColor(textDim).fontSize(10).text(
            `Generated by Antigravity AI | Project: Krishna says`,
            50,
            750,
            { align: 'center' }
        );
    };

    // Add footer to first page
    addFooter(doc);

    // --- TEST RESULTS ---
    if (fs.existsSync(path.join(__dirname, 'test_output.txt'))) {
        doc.addPage();
        addFooter(doc);
        doc.fillColor(primary).fontSize(18).text('Validation & Test Results', { underline: true });
        doc.moveDown(0.5);
        const testOutput = fs.readFileSync(path.join(__dirname, 'test_output.txt'), 'utf8');
        doc.fillColor(textDim).fontSize(9).text(testOutput.substring(0, 3000), { font: 'Courier' });
    }

    doc.end();

    stream.on('finish', () => {
        console.log(`Premium PDF generated successfully at: ${outputPath}`);
    });
}

generatePDF();
